config/routes.rb
Rails.application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  devise_for :admin_users, ActiveAdmin::Devise.config.merge(
    class_name: 'User', as: 'admin',
    skip: [:confirmations, :passwords, :registrations, :unlocks, :omniauth_callbacks],
    controllers: {sessions: 'sessions'}
  )
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { registrations: 'registrations',
                                       sessions: 'sessions',
                                       :passwords => "passwords",
                                       omniauth_callbacks: "omniauth_callbacks" }

  root 'home#index'

  devise_scope :user do
    get '/users/sign_out' => 'sessions#destroy'
    get 'alliance_registration', :to => 'registrations#new_alliance'
    get 'business_registration', :to => 'registrations#new_business'
    get 'church_registration', :to => 'registrations#new_church'
    get 'alliance_edit', :to => 'registrations#edit_alliance'
    get 'business_edit', :to => 'registrations#edit_business'
    get 'church_edit', :to => 'registrations#edit_church'

    # get '/users/sign_up/alliance', :to => 'registrations#new_alliance'
    # get '/users/sign_up/business', :to => 'registrations#new_business'
    # get '/users/sign_up/church', :to => 'registrations#new_church'
    # get '/users/edit_alliance', :to => 'registrations#edit_alliance'
  end

  get 'calendar' => 'events#index'
  resources :events,      only:  [:new, :create, :show] do
      resources :attendees,   only:  [:new, :create]
      resource :download_badges_pdf, only: [:show]
  end
  resources :alliances,   only:  [:index, :show, :edit, :update]
  resources :businesses,  only:  [:index, :show, :edit, :update]
  resources :churches,    only:  [:index, :show, :edit, :update]
  resources :users,       only:  [:edit, :update]
  resources :payments,    only:  [:new, :create]
  resources :ads,         only:  [:new, :create, :edit, :update]
  resources :invites,     only:  [:new, :create]

  resources :campaigns,   only:  [:index, :show, :new, :create] do
      resources :campaign_donations, only: [:new, :create]
  end

  resources :charitable_donations, only: [:new, :create]

  resources :chamber_donations, only: [:new, :create]

  resources :needs,       only: [:new, :create, :show] do
      resources :resources,          only: [:new, :create]
  end

  resources :resources,   only: [:new, :create] do
    get :accept, on: :member
  end

  # Temporary Hidden
  # resources :job_leads, only: [:new, :create]

  get 'dashboard(/:user_id)' => 'users#dashboard', as: :dashboard

  #---------------- Tool Box Links ------------------
  get 'tool_boxes' => 'tool_boxes#index'
  get 'tool_box' => 'tool_boxes#show'

  get 'documents' => 'tool_boxes#documents'
  get 'tool_box_resources' => 'tool_boxes#resources'
  get 'tool_box_events' => 'tool_boxes#events'

  get 'blog' => 'tool_boxes#blog', as: :blog
  #--------------------------------------------------

  # #---------------- Invite  Links ------------------
  # get "invite/new" => 'invite#new', :as => :new_invite
  # post "invite/create" => 'invite#create', :as => :invites
  # #---------------------------------------------------

  get 'docs' => 'home#save_docs'

  get 'contact_us' =>  'contact_form#new'
  resources "contact_forms", only: [:new, :create]
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    scope = Business.all.approved
    if params[:search]
      @businesses = scope.where('name ILIKE ?', "%#{params[:search]}%")
    elsif params[:category_search]
      @businesses = scope.where(business_category_id: params[:category_search])
    elsif params[:region_search]
      @businesses = scope.where(region_id: params[:region_search])
    else
      @businesses = scope
    end
    render layout: "landing_page"
  end

  def show
    @business= Business.find(params[:id])
    render layout: "landing_page"
  end

  def edit
    @business = Business.find(params[:id])
    authorize @business
    render layout: "form_page"
  end

  def update
    @business = Business.find(params[:id])
    authorize @business
    if @business.update_attributes(business_params)
     flash[:success] = "Business Updated!"
     redirect_to @business
    else
      render 'edit'
    end
  end

  private
  def business_params
    params.require(:business).permit(:contact_email, :name, :description, :region_id, :logo, :church_category_id, :website_url, :facebook_url, :twitter_url, :gplus_url)
  end
end

app/views/businesses/edit.html.erb
<div class="top-content">
  <div class="container" style="background: #a3cbdb; width:100%; min-height:100vh; padding-top:100px;">
    <p style="margin-top:0; margin-bottom:0; font-family: 'Lato'; font-size: 50px; font-weight: 300 !important; text-align:center; text-transform: uppercase; font-weight:500">Business</p>
    <p style="margin-top:0; text-align:center; font-variant: small-caps; font-weight:300; font-size: 20px">edit account</p>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 form-box" style="padding-bottom: 50px">
        	<%= form_for(@business,  html: { class: 'f1'}) do |f| %>
        		<div class="f1-steps">
        			<div class="f1-progress">
        			    <div class="f1-progress-line" data-now-value="12" data-number-of-steps="1" style="width: 100%;"></div>
        			</div>
        			<div class="f1-step active" style="width:100%">
        				<div class="f1-step-icon"><i class="fa fa-user"></i></div>
        			</div>
        		</div>
            <h4 style="color: #26344b; margin-bottom:0; font-family:'Lato'; text-transform:uppercase; text-align:center; font-weight:300;">Basic Info</h4>
            <div class="form-group form-md-line-input  form-md-floating-label" style="padding-bottom: 0px; margin-bottom:0; padding-top: 35px;">
              <div class="input-icon right">
                  <%= f.text_field :name, class: "form-control" %>
                  <%= f.label :name %>
                  <i class="fa fa-user"></i>
              </div>
            </div>
            <div class="form-group form-md-line-input  form-md-floating-label" style="padding-bottom: 0px; margin-bottom:0; padding-top: 35px;">
              <div class="input-icon right">
                  <%= f.email_field :contact_email, class: "form-control" %>
                  <%= f.label :contact_email %>
                  <i class="fa fa-envelope-o"></i>
              </div>
            </div>
            <div class="form-group form-md-line-input form-md-floating-label" style="margin-top:15px;">
                <%= f.text_area :description, class: 'form-control', rows: 3 %>
                <%= f.label :description %>
            </div>

            <div class="row">
              <div class="form-group ">
                <div class="col-xs-12 col-md-8 col-md-offset-2" style="text-align:center">
                  <h4 style="color:#555">Logo Image Upload</h4>
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                            <img src="<%= @business.logo? ? @business.logo.url : 'http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image' %>" alt="" />
                        </div>
                        <div>
                          <span class="btn red btn-outline btn-file">
                              <span class="fileinput-new"> Select image </span>
                              <span class="fileinput-exists"> Change </span>
                              <%= f.file_field :logo %>
                            </span>
                            <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Remove </a>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
              <hr />
              <h4 style="color: #26344b; margin-bottom:0; font-family:'Lato'; text-transform:uppercase; text-align:center; font-weight:300;">Associations</h4>

              <div class="form-group form-md-line-input" style="padding-bottom: 0px; margin-bottom:0; padding-top: 32px;">
                <%= f.label :region_id %>
                <%= f.collection_select :region_id, Region.order(:name), :id, :name, {prompt: true}, {class: 'select-business-category', style: 'margin-top: 10px;'} %>
              </div>

              <div class="form-group form-md-line-input" style="padding-bottom: 0px; margin-bottom:0; padding-top: 32px;">
                <%= f.label :business_category_id %>
                <%= f.collection_select :business_category_id, BusinessCategory.order(:name), :id, :name, {prompt: true}, {class: 'select-business-category', style: 'margin-top: 10px;'} %>
              </div>

              <div class="form-group form-md-line-input  form-md-floating-label" style="padding-bottom: 0px; margin-bottom:0; padding-top: 35px;">
                <div class="input-icon right">
                    <%= f.url_field :website_url, class: "form-control" %>
                    <%= f.label :website_url %>
                    <i class="fa fa-globe"></i>
                </div>
              </div>

              <div class="form-group form-md-line-input  form-md-floating-label" style="padding-bottom: 0px; margin-bottom:0; padding-top: 35px;">
                <div class="input-icon right">
                    <%= f.url_field :facebook_url, class: "form-control" %>
                    <%= f.label :facebook_url %>
                    <i class="fa fa-facebook"></i>
                </div>
              </div>

              <div class="form-group form-md-line-input  form-md-floating-label" style="padding-bottom: 0px; margin-bottom:0; padding-top: 35px;">
                <div class="input-icon right">
                    <%= f.url_field :twitter_url, class: "form-control" %>
                    <%= f.label :twitter_url %>
                    <i class="fa fa-twitter"></i>
                </div>
              </div>
              <div class="form-group form-md-line-input  form-md-floating-label" style="padding-bottom: 0px; margin-bottom:0; padding-top: 35px;">
                <div class="input-icon right">
                    <%= f.url_field :gplus_url, class: "form-control" %>
                    <%= f.label :google_plus_url %>
                    <i class="fa fa-google-plus"></i>
                </div>
              </div>
              <div class="row" style="padding-right:0">
                <%= f.submit 'Confirm Edit', class: "btn btn-dark btn-submit", style: "margin-bottom:0; width:100%;padding:10px"%>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/businesses/index.html.erb
<!-- begin Content -->
<section id="business-index" class="section-home" style="min-height:95vh; background: #a3cbdb;">
  <div class="container show-container">
    <h2 class="show-title" style="color:white; padding-bottom:20px">Business Members</h2>
    	<article class="donations">
      <div class="col-md-4 col-lg-3" style="padding:10px; background:white; border-radius: 5px; margin-bottom: 10px;">
        <%= form_tag businesses_path, :method => 'get' do %>
          <div class="input-group" style="width:100%">
            <%= text_field_tag :search, nil, class: "form-control", placeholder: "Search for..." %>
            <%= submit_tag "Search", name: nil, style: "border:0; padding:0; font-size:0" %>
          </div>
        <% end %>

        <div class="row" style="margin:0; margin-top:10px;">
          <a href="#business_category_search" style="color: #26344b; font-size: 18px; text-transform:uppercase; margin: 20px 0 10px 0;" data-toggle="collapse">
            <i class="icon-plus"></i>
            Categories
          </a>
        </div>

        <ul id="business_category_search" class="categories collapse">
          <% BusinessCategory.all.each do |category| %>
            <li>
              <%= link_to businesses_path(request.query_parameters.merge({:category_search => category.id}).except(:search, :region_search)) do %>
                <i class="icon-plus"></i><%= category.name %><span class="pull-right"></span>
              <% end %>
            </li>
          <% end %>
        </ul>

        <div class="row" style="margin:0;">
           <a href="#business_region_search" style="color: #26344b; font-size: 18px; text-transform:uppercase; margin: 20px 0 10px 0;" data-toggle="collapse">
             <i class="icon-plus"></i>
             Regions
           </a>
         </div>

         <ul id="business_region_search" class="categories collapse">
          <% Region.all.each do |region| %>
            <li>
              <%= link_to businesses_path(request.query_parameters.merge({:region_search => region.id}).except(:search, :category_search)) do %>
                <i class="icon-plus"></i><%= region.name %><span class="pull-right"></span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>

    	<div class="col-md-8 col-lg-9" style="margin-bottom: 20px;">
    		<div class="row">
          <%- if @businesses.present? %>
            <% @businesses.each do |business| %>
          		<div class="col-lg-4 col-sm-6">
                <%= link_to business, class: "donation-item", style: "text-decoration: none; border-radius: 8px;" do %>
                  <figure>
                    <%- if business.logo?%>
                      <%= image_tag business.logo.url, class:"landing-page-campaign-image", style: "border-radius: 8px 8px 0 0;"%>
                    <% else %>
                      <img src="//placehold.it/400x300" class="landing-page-campaign-image" style="border-radius: 8px 8px 0 0;">
                    <% end %>
          				</figure>
          				<div class="content landing-page-campaign-content" style="height: 150px; border-bottom:0">
          					<h4><%= business.name %></h4>
          					<p><%= business.description %></p>
          				</div>
                  <div class="foot" style="padding-bottom:0px">
                  </div>
          			<% end %>
          		</div>
            <% end %>
          <% else %>
              <div class="col-xs-8 col-xs-offset-2 text-center" style="background: white; padding: 20px; margin-top:5vh; border-radius:5px">
                <h3 style="font-family: 'Lato'; font-weight:300; text-transform:uppercase; margin-top: 20px; text-align:center">No Businesses Found</h3>
                <%= link_to 'Reset Search Results', businesses_path, class: "btn btn-dark" %>
          		</div>
          <% end %>
    		</div>
    	</div>
    </div>
	</article>
</section>

app/views/businesses/show.html.erb
<!-- begin Content -->
<section id="business-show" class="section-home" style="min-height:95vh; background: #a3cbdb;">
  <div class="container show-container">
    <h2 class="show-title" style="color:white"><%= @business.name %></h2>
    <section class="show-section">
      <div class="col-sm-6 col-md-8" style="">
        <div class="row" style="text-align:center">
          <%- if @business.logo?%>
            <%= image_tag @business.logo.url, style: "padding: 30px; width: 90%;" %>
          <% else %>
            <img src="//placehold.it/400x300" style= "padding: 30px; width: 90%;">
          <% end %>
        </div>
        <div class="row" style="width:80%; margin-left:10%">
          <p>
            <%= @business.description %>
          </p>
        </div>
        <div class="row" style="text-align:center">
          <%= link_to "Our Website", @business.website_url, class: "btn btn-dark", style: "margin-top: 10px;", :target => "_blank" %>
        </div>
      </div>
      <div class="col-sm-6 col-md-4">
        <h4>Social Media</h4>
        <ul class="social" style="font-size: .8em;">
					<li><a href="<%= @business.facebook_url %>" class="facebook"><i class="icon-facebook"></i><span style="font-size:.7em">Follow Us On Facebook</span></a></li>
					<li><a href="<%= @business.twitter_url %>" class="twitter"><i class="icon-twitter"></i><span style="font-size:.7em">Follow Us On Twitter</span></a></li>
					<li><a href="<%= @business.gplus_url %>" class="gplus"><i class="icon-gplus"></i><span style="font-size:.7em">Follow Us On GPlus</span></a></li>
				</ul>
        <hr />
        <h4>Categories</h4>
        <ul class="categories">
          <li><a href="#"><i class="icon-plus"></i><%= @business.business_category.try(:name) %></a></li>
				</ul>
      </div>
    </section>
  </div>
</section>
<!-- end Content -->