config/routes.rb
Rails.application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  devise_for :admin_users, ActiveAdmin::Devise.config.merge(
    class_name: 'User', as: 'admin',
    skip: [:confirmations, :passwords, :registrations, :unlocks, :omniauth_callbacks],
    controllers: {sessions: 'sessions'}
  )
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { registrations: 'registrations',
                                       sessions: 'sessions',
                                       :passwords => "passwords",
                                       omniauth_callbacks: "omniauth_callbacks" }

  root 'home#index'

  devise_scope :user do
    get '/users/sign_out' => 'sessions#destroy'
    get 'alliance_registration', :to => 'registrations#new_alliance'
    get 'business_registration', :to => 'registrations#new_business'
    get 'church_registration', :to => 'registrations#new_church'
    get 'alliance_edit', :to => 'registrations#edit_alliance'
    get 'business_edit', :to => 'registrations#edit_business'
    get 'church_edit', :to => 'registrations#edit_church'

    # get '/users/sign_up/alliance', :to => 'registrations#new_alliance'
    # get '/users/sign_up/business', :to => 'registrations#new_business'
    # get '/users/sign_up/church', :to => 'registrations#new_church'
    # get '/users/edit_alliance', :to => 'registrations#edit_alliance'
  end

  get 'calendar' => 'events#index'
  resources :events,      only:  [:new, :create, :show] do
      resources :attendees,   only:  [:new, :create]
      resource :download_badges_pdf, only: [:show]
  end
  resources :alliances,   only:  [:index, :show, :edit, :update]
  resources :businesses,  only:  [:index, :show, :edit, :update]
  resources :churches,    only:  [:index, :show, :edit, :update]
  resources :users,       only:  [:edit, :update]
  resources :payments,    only:  [:new, :create]
  resources :ads,         only:  [:new, :create, :edit, :update]
  resources :invites,     only:  [:new, :create]

  resources :campaigns,   only:  [:index, :show, :new, :create] do
      resources :campaign_donations, only: [:new, :create]
  end

  resources :charitable_donations, only: [:new, :create]

  resources :chamber_donations, only: [:new, :create]

  resources :needs,       only: [:new, :create, :show] do
      resources :resources,          only: [:new, :create]
  end

  resources :resources,   only: [:new, :create] do
    get :accept, on: :member
  end

  # Temporary Hidden
  # resources :job_leads, only: [:new, :create]

  get 'dashboard(/:user_id)' => 'users#dashboard', as: :dashboard

  #---------------- Tool Box Links ------------------
  get 'tool_boxes' => 'tool_boxes#index'
  get 'tool_box' => 'tool_boxes#show'

  get 'documents' => 'tool_boxes#documents'
  get 'tool_box_resources' => 'tool_boxes#resources'
  get 'tool_box_events' => 'tool_boxes#events'

  get 'blog' => 'tool_boxes#blog', as: :blog
  #--------------------------------------------------

  # #---------------- Invite  Links ------------------
  # get "invite/new" => 'invite#new', :as => :new_invite
  # post "invite/create" => 'invite#create', :as => :invites
  # #---------------------------------------------------

  get 'docs' => 'home#save_docs'

  get 'contact_us' =>  'contact_form#new'
  resources "contact_forms", only: [:new, :create]
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user

  after_create :update_user_expiration

  private
  def update_user_expiration
    expiration = [user.expiration, Time.now].compact.max + 1.year
    user.update_attribute :expiration, expiration
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  layout "form_page"

  before_filter :authenticate_user!

  skip_before_filter :redirect_to_payment

  def new
    @amount = current_user.try :membership_fee
  end

  def create
    amount = current_user.membership_fee
    application_fee = ((amount * 0.054) + 30).to_i
    super_admin = nil
    User.all.each do |user|
      if user.super_admin?
        super_admin = user;
      end
    end
    puts "AMOUNT::" + amount.to_s
    puts "APPLICATION FEE::" + application_fee.to_s
    puts "ADMIN ID::" + super_admin.stripe_user_id.to_s

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => amount,
      :description => 'SC Christian Chamber of Commerce - Membership Dues',
      :currency    => 'usd',
      :application_fee => application_fee,
      :destination => super_admin.stripe_user_id
    )

    current_user.payments.create(
      :amount => amount,
      :charge_id => charge.id,
      :card_token => charge.source.id
    )
    
    flash[:notice] = 'Your payment was successful'
    redirect_to dashboard_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_payment_path
  end
end

app/views/payments/new.html.erb
<div class="top-content">
  <div class="container" style="background: #a3cbdb; min-height:95vh; padding-top:90px;">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 form-box" style="padding:25px; background: white; ">
        <p style="color: red; margin-top:0; margin-bottom:0; font-family: 'Lato'; font-size: 50px; font-weight: 200 !important; text-align:center; text-transform: uppercase;">Checkout</p>
        <div class="f1-steps" style="margin-top:0">
          <div class="f1-progress">
              <div class="f1-progress-line" data-now-value="100" data-number-of-steps="1" style="width: 100%;"></div>
          </div>
          <div class="f1-step active" style="width:100%">
            <div class="f1-step-icon"><i class="fa fa-usd"></i></div>
          </div>
        </div>
        <p class="text-center" style="color:gray; font-size:12px; padding:15px">
          <% if current_user.expiration.nil? %>
            Thanks for joining us at South Carolina Christian Chamber of Commerce! Please submit a payment below using our secure Stripe checkout.
          <% elsif current_user.expiration < Time.now %>
            Your membership has expired. Please make a payment to access your account.
          <% else %>
            You can renew your membership early from this page. After submitting a payment below, a year will be added to your account expiration date.
            <p class="text-center" style="color:gray; font-size:12px; padding:15px">
              <b>New Account Exp. Date:</b> <%= (current_user.expiration + 365.days).strftime("%m/%d/%Y") %>
            </p>
          <% end %>
        </p>
        <div class="row text-center">
        <%= form_tag payments_path, method: :post %>
          <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-amount="<%= @amount %>"
            data-name="SC Christian Chamber of Commerce"
            data-email="<%= current_user.email %>"
            data-description="Annual membership"
            data-image="https://s3.amazonaws.com/sc-c3/sc-c3-logo-square.png"
            data-locale="auto"
            data-zip-code="true">
          </script>
        </form>
      </div>
    </div>
  </div>
</div>
</div>